version: "2.0"
services:
  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - /mnt/mongodb/:/data/db
  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - /mnt/redis/:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image:  rabbitmq:3.6.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /mnt/rabbitmq/:/var/rabbitmq/lib
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=control-manger
  control-manger:
    image: control-manger:latest
    ports:
      - "8081:8081"
    links:
      - mongodb
      - redis
      - rabbitmq
    depends_on:
      - mongodb
      - redis
      - rabbitmq
  control-manger-config:
    image: control-manger-config:latest
    ports:
      - "8888:8888"
    links:
      - control-manger
    depends_on:
      - control-manger