## redis配置
spring:
  redis:
    pool:
      max-idle: 10
      min-idle: 0
      max-wait: 5000
      max-active: 8
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: control-manger
## quartz配置
org:
  quartz:
    threadPool:
      clazz:  org.quartz.simpl.SimpleThreadPool
      threadCount:  20
      threadPriority: 5
      threadNamePrefix: control_manger
